version: 2
updates:
- package-ecosystem: nuget
  directory: "/BootstrapEmailNet/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "BootstrapEmailNet.Tests"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "BootstrapEmail.Net.Benchmarks"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10